### PR TITLE
Fixed typo `object` to `Object`

### PR DESCRIPTION
**Pull request by pyrho**

### CODE REVIEW

**Comment by dphilipson** [comment]
Hi pyrho, thank you very much for the contribution!

`object` is actually intended. It was added in TypeScript 2.2 ([release notes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-2.html)) and refers to non-primitive objects, by contrast to the type `Object` which is the interface with methods like `hasOwnProperty`, `toString`, etc.

If you're seeing errors on this, it means your TypeScript is pre-2.2. I would be willing to consider changing this to ensure compatibility with pre-2.2 TypeScript, but since the library needs at least 2.1 to work at all, my assumption was that it would be okay to require a newer version rather than accommodating the narrow range of 2.1 <= version < 2.2.

I could be wrong: there may be a large segment of users who are on 2.1 but not 2.2. Do you know if this would be the case? If so, please open an issue for wider visibility of this discussion.

**Comment by pyrho** [comment]
Hi @dphilipson !

Thanks for the reply, I missed the release announcement regarding 2.2 (and the [typescript playground](https://www.typescriptlang.org/play/) gave an error for `object` too) ! I will upgrade to 2.2.

But regardless of that, I think that following [semver](http://semver.org), the pacakge number should be a major update (ie. 1.0.0) because it's API breaking (ie. it used to work with TS2.1 but doesn't with TS2.2, so people `npm install` installing "today" will have a breaking change, when it was working for them "yesterday").

Thank you again.

**Comment by dphilipson** [comment]
FYI, according to semver if the version is pre-1.0.0, then any release is allowed to be breaking. Still, what you said is noted, and it might be time for a 1.0.0 release soon.

Thanks!

**Comment by pyrho** [comment]
Oh I wasn't aware of this, thanks !

**Pull request closed without merging**
